PROJECT_NAME = MeshBean
CONFIG_NAME = All_ZigBit_Atmega1281_Rf230_8Mhz_Gcc

#CONFIG_NAME = All_Rcb_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Rcb_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Router_Rcb_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = All_Sec_Rcb_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Sec_Rcb_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Router_Sec_Rcb_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = All_Rcb_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Coordinator_Rcb_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Router_Rcb_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = All_Sec_Rcb_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Coordinator_Sec_Rcb_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Router_Sec_Rcb_Atmega1281_Rf230_8Mhz_Iar
#PROJECT_NAME = RCB230

#CONFIG_NAME = All_Rcb_Atmega1281_Rf231_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Rcb_Atmega1281_Rf231_8Mhz_Gcc
#CONFIG_NAME = Router_Rcb_Atmega1281_Rf231_8Mhz_Gcc
#CONFIG_NAME = All_Sec_Rcb_Atmega1281_Rf231_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Sec_Rcb_Atmega1281_Rf231_8Mhz_Gcc
#CONFIG_NAME = Router_Sec_Rcb_Atmega1281_Rf231_8Mhz_Gcc
#CONFIG_NAME = All_Rcb_Atmega1281_Rf231_8Mhz_Iar
#CONFIG_NAME = Coordinator_Rcb_Atmega1281_Rf231_8Mhz_Iar
#CONFIG_NAME = Router_Rcb_Atmega1281_Rf231_8Mhz_Iar
#CONFIG_NAME = All_Sec_Rcb_Atmega1281_Rf231_8Mhz_Iar
#CONFIG_NAME = Coordinator_Sec_Rcb_Atmega1281_Rf231_8Mhz_Iar
#CONFIG_NAME = Router_Sec_Rcb_Atmega1281_Rf231_8Mhz_Iar
#PROJECT_NAME = RCB231

#CONFIG_NAME = All_ZigBit_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = Coordinator_ZigBit_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = Router_ZigBit_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = All_Sec_ZigBit_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Sec_ZigBit_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = Router_Sec_ZigBit_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = All_ZigBit_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = Coordinator_ZigBit_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = Router_ZigBit_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = All_Sec_ZigBit_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = Coordinator_Sec_ZigBit_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = Router_Sec_ZigBit_Atmega1281_Rf212_8Mhz_Iar
#PROJECT_NAME = MeshBean_900

#CONFIG_NAME = All_Rcb_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Rcb_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = Router_Rcb_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = All_Sec_Rcb_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Sec_Rcb_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = Router_Sec_Rcb_Atmega1281_Rf212_8Mhz_Gcc
#CONFIG_NAME = All_Rcb_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = Coordinator_Rcb_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = Router_Rcb_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = All_Sec_Rcb_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = Coordinator_Sec_Rcb_Atmega1281_Rf212_8Mhz_Iar
#CONFIG_NAME = Router_Sec_Rcb_Atmega1281_Rf212_8Mhz_Iar
#PROJECT_NAME = RCB212

#CONFIG_NAME = All_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Coordinator_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Router_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = All_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Router_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = All_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Coordinator_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Router_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = All_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Coordinator_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Router_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#PROJECT_NAME = MeshBean

#CONFIG_NAME = All_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Coordinator_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Router_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = All_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Coordinator_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = Router_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Gcc
#CONFIG_NAME = All_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Coordinator_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Router_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = All_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Coordinator_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#CONFIG_NAME = Router_Sec_ZigBit_Atmega1281_Rf230_8Mhz_Iar
#PROJECT_NAME = MeshBean_Amp

all:
	make -C makefiles/$(PROJECT_NAME) -f Makefile_$(CONFIG_NAME) all

clean:
	make -C makefiles/$(PROJECT_NAME) -f Makefile_$(CONFIG_NAME) clean
